### ISSUE TITLE
A whole bunch of errors

### ISSUE THREAD

**Issue by kpennell** [scrapinghub/portia2code#9]
I followed [your instructions](https://blog.scrapinghub.com/2016/06/29/introducing-portia2code-portia-projects-into-scrapy-spiders/) but no dice. Any ideas what's up with these errors?

```
/Library/Python/2.7/site-packages/slybot/plugins/scrapely_annotations/builder.py:366: ScrapyDeprecationWarning: Attribute `_root` is deprecated, use `root` instead
  elems = [elem._root for elem in self.selector.css(selector)]
Traceback (most recent call last):
  File "/usr/local/bin/portia_porter", line 42, in <module>
    schemas, extractors, spiders = load_project_data(Storage(project_dir))
  File "/Library/Python/2.7/site-packages/portia2code/porter.py", line 76, in load_project_data
    Settings())
  File "/Library/Python/2.7/site-packages/slybot/spider.py", line 58, in __init__
    settings, spec, item_schemas, all_extractors)
  File "/Library/Python/2.7/site-packages/slybot/spider.py", line 226, in _configure_plugins
    self.logger)
  File "/Library/Python/2.7/site-packages/slybot/plugins/scrapely_annotations/annotations.py", line 89, in setup_bot
    self.extractors.append(SlybotIBLExtractor(list(group)))
  File "/Library/Python/2.7/site-packages/slybot/plugins/scrapely_annotations/extraction/extractors.py", line 61, in __init__
    for p, v in zip(parsed_templates, template_versions)
  File "/Library/Python/2.7/site-packages/slybot/plugins/scrapely_annotations/extraction/extractors.py", line 70, in build_extraction_tree
    basic_extractors = ContainerExtractor.apply(template, basic_extractors)
  File "/Library/Python/2.7/site-packages/slybot/plugins/scrapely_annotations/extraction/container_extractors.py", line 65, in apply
    extraction_tree = cls._build_extraction_tree(containers)
  File "/Library/Python/2.7/site-packages/slybot/plugins/scrapely_annotations/extraction/container_extractors.py", line 144, in _build_extraction_tree
    parent = containers[parent_id]
KeyError: u'2de2-4d1f-97ab#parent'

```

**Comment by kpennell** [comment]
Not sure what to try. Tried different virtualenv, pip2 vs. pip3. Could use some help before I rabbit hole too much further.
